<?php
/**
 * Created by PhpStorm.
 * Author: Alexey Tishchenko
 * Email: tischenkoalexey1@gmail.com
 * oDesk: https://www.odesk.com/users/%7E01ad7ed1a6ade4e02e
 * Date: 03.11.14
 */
namespace sjoorm\yii\components\helpers;
use sjoorm\yii\components\interfaces\PrintableRecordInterface;
use yii\base\Model;
use yii\db\ActiveRecord;
/**
 * Class Misc describes common widely-used functions
 * @package sjoorm\yii\components\helpers
 */
class Misc {

    /**
     * Formats associative array of attributes to string for email body insertion
     * @param ActiveRecord $model
     * @param boolean $html
     * @return string
     */
    public static function attributesToString(ActiveRecord $model, $html = true) {
        $result = '';

        $delimiter = $html ? "<br/>\n" : "\n";
        $attributes = $model instanceof PrintableRecordInterface ?
            $model->getAttributesToPrint($html) : $model->attributes;
        foreach($attributes as $key => $value) {
            if(is_array($value)) {
                $value = json_encode($value);
            }
            $label = $model->getAttributeLabel($key);
            $result .= "<strong>$label:</strong> $value $delimiter";
        }

        return $result;
    }

    /**
     * Extracts Model errors from array and puts them into string
     * @param Model $model
     * @param boolean $html
     * @return string
     */
    public static function errorsToString($model, $html = true) {
        $result = '';

        $delimiter = $html ? "<br/>\n" : "\n";
        foreach($model->errors as $attribute => $error) {
            $errors = implode(', ', $error);
            $result .= $model->getAttributeLabel($attribute) . ": {$errors}{$delimiter}";
        }

        return $result;
    }

    /**
     * Returns element of an array by specified key
     * Or returns shifted one, if key is not specified
     * @param mixed $array
     * @param string|integer $key
     * @return mixed
     */
    public static function getByKey($array, $key = null) {
        return empty($array) ?
            null :
            (is_array($array) ?
                (isset($array[$key]) ?
                    $array[$key] :
                    array_shift($array)) :
                $array
            );
    }

    /**
     * Gets list of ISO-3166-Alpha-2 country codes and names
     * @param string|null $language
     * @return array
     */
    public static function getCountryCodes($language = null) {
        $result = null;

        $language = $language ?: \Yii::$app->language;
        switch($language) {
            case 'de-DE':
                $result = [
                    'EG' => 'Ägypten',
                    'AF' => 'Afghanistan',
                    'AX' => 'Alandinseln',
                    'AL' => 'Albanien',
                    'DZ' => 'Algerien',
                    'UM' => 'Amerikanisch-Ozeanien',
                    'AS' => 'Amerikanisch-Samoa',
                    'VI' => 'Amerikanische Jungferninseln',
                    'AD' => 'Andorra',
                    'AO' => 'Angola',
                    'AI' => 'Anguilla',
                    'AQ' => 'Antarktis',
                    'AG' => 'Antigua und Barbuda',
                    'GQ' => 'Äquatorialguinea',
                    'AR' => 'Argentinien',
                    'AM' => 'Armenien',
                    'AW' => 'Aruba',
                    'AZ' => 'Aserbaidschan',
                    'ET' => 'Äthiopien',
                    'AU' => 'Australien',
                    'BS' => 'Bahamas',
                    'BH' => 'Bahrain',
                    'BD' => 'Bangladesch',
                    'BB' => 'Barbados',
                    'BY' => 'Belarus',
                    'BE' => 'Belgien',
                    'BZ' => 'Belize',
                    'BJ' => 'Benin',
                    'BM' => 'Bermuda',
                    'BT' => 'Bhutan',
                    'BO' => 'Bolivien',
                    'BA' => 'Bosnien und Herzegowina',
                    'BW' => 'Botsuana',
                    'BV' => 'Bouvetinsel',
                    'BR' => 'Brasilien',
                    'VG' => 'Britische Jungferninseln',
                    'IO' => 'Britisches Territorium im Indischen Ozean',
                    'BN' => 'Brunei Darussalam',
                    'BG' => 'Bulgarien',
                    'BF' => 'Burkina Faso',
                    'BI' => 'Burundi',
                    'CL' => 'Chile',
                    'CN' => 'China',
                    'CK' => 'Cookinseln',
                    'CR' => 'Costa Rica',
                    'CI' => 'Côte d’Ivoire',
                    'CD' => 'Demokratische Republik Kongo',
                    'KP' => 'Demokratische Volksrepublik Korea',
                    'DE' => 'Deutschland',
                    'DM' => 'Dominica',
                    'DO' => 'Dominikanische Republik',
                    'DJ' => 'Dschibuti',
                    'DK' => 'Dänemark',
                    'EC' => 'Ecuador',
                    'SV' => 'El Salvador',
                    'ER' => 'Eritrea',
                    'EE' => 'Estland',
                    'FK' => 'Falklandinseln',
                    'FJ' => 'Fidschi',
                    'FI' => 'Finnland',
                    'FR' => 'Frankreich',
                    'GF' => 'Französisch-Guayana',
                    'PF' => 'Französisch-Polynesien',
                    'TF' => 'Französische Süd- und Antarktisgebiete',
                    'FO' => 'Färöer',
                    'GA' => 'Gabun',
                    'GM' => 'Gambia',
                    'GE' => 'Georgien',
                    'GH' => 'Ghana',
                    'GI' => 'Gibraltar',
                    'GD' => 'Grenada',
                    'GR' => 'Griechenland',
                    'GL' => 'Grönland',
                    'GP' => 'Guadeloupe',
                    'GU' => 'Guam',
                    'GT' => 'Guatemala',
                    'GG' => 'Guernsey',
                    'GN' => 'Guinea',
                    'GW' => 'Guinea-Bissau',
                    'GY' => 'Guyana',
                    'HT' => 'Haiti',
                    'HM' => 'Heard- und McDonald-Inseln',
                    'HN' => 'Honduras',
                    'IN' => 'Indien',
                    'ID' => 'Indonesien',
                    'IQ' => 'Irak',
                    'IR' => 'Iran',
                    'IE' => 'Irland',
                    'IS' => 'Island',
                    'IM' => 'Isle of Man',
                    'IL' => 'Israel',
                    'IT' => 'Italien',
                    'JM' => 'Jamaika',
                    'JP' => 'Japan',
                    'YE' => 'Jemen',
                    'JE' => 'Jersey',
                    'JO' => 'Jordanien',
                    'KY' => 'Kaimaninseln',
                    'KH' => 'Kambodscha',
                    'CM' => 'Kamerun',
                    'CA' => 'Kanada',
                    'CV' => 'Kap Verde',
                    'KZ' => 'Kasachstan',
                    'QA' => 'Katar',
                    'KE' => 'Kenia',
                    'KG' => 'Kirgisistan',
                    'KI' => 'Kiribati',
                    'CC' => 'Kokosinseln',
                    'CO' => 'Kolumbien',
                    'KM' => 'Komoren',
                    'CG' => 'Kongo',
                    'HR' => 'Kroatien',
                    'CU' => 'Kuba',
                    'KW' => 'Kuwait',
                    'LA' => 'Laos',
                    'LS' => 'Lesotho',
                    'LV' => 'Lettland',
                    'LB' => 'Libanon',
                    'LR' => 'Liberia',
                    'LY' => 'Libyen',
                    'LI' => 'Liechtenstein',
                    'LT' => 'Litauen',
                    'LU' => 'Luxemburg',
                    'MG' => 'Madagaskar',
                    'MW' => 'Malawi',
                    'MY' => 'Malaysia',
                    'MV' => 'Malediven',
                    'ML' => 'Mali',
                    'MT' => 'Malta',
                    'MA' => 'Marokko',
                    'MH' => 'Marshallinseln',
                    'MQ' => 'Martinique',
                    'MR' => 'Mauretanien',
                    'MU' => 'Mauritius',
                    'YT' => 'Mayotte',
                    'MK' => 'Mazedonien',
                    'MX' => 'Mexiko',
                    'FM' => 'Mikronesien',
                    'MC' => 'Monaco',
                    'MN' => 'Mongolei',
                    'ME' => 'Montenegro',
                    'MS' => 'Montserrat',
                    'MZ' => 'Mosambik',
                    'MM' => 'Myanmar',
                    'NA' => 'Namibia',
                    'NR' => 'Nauru',
                    'NP' => 'Nepal',
                    'NC' => 'Neukaledonien',
                    'NZ' => 'Neuseeland',
                    'NI' => 'Nicaragua',
                    'NL' => 'Niederlande',
                    'AN' => 'Niederländische Antillen',
                    'NE' => 'Niger',
                    'NG' => 'Nigeria',
                    'NU' => 'Niue',
                    'NF' => 'Norfolkinsel',
                    'NO' => 'Norwegen',
                    'MP' => 'Nördliche Marianen',
                    'OM' => 'Oman',
                    'AT' => 'Österreich',
                    'TL' => 'Osttimor',
                    'PK' => 'Pakistan',
                    'PW' => 'Palau',
                    'PS' => 'Palästinensische Gebiete',
                    'PA' => 'Panama',
                    'PG' => 'Papua-Neuguinea',
                    'PY' => 'Paraguay',
                    'PE' => 'Peru',
                    'PH' => 'Philippinen',
                    'PN' => 'Pitcairn',
                    'PL' => 'Polen',
                    'PT' => 'Portugal',
                    'PR' => 'Puerto Rico',
                    'KR' => 'Republik Korea',
                    'MD' => 'Republik Moldau',
                    'RW' => 'Ruanda',
                    'RO' => 'Rumänien',
                    'RU' => 'Russische Föderation',
                    'RE' => 'Réunion',
                    'SB' => 'Salomonen',
                    'ZM' => 'Sambia',
                    'WS' => 'Samoa',
                    'SM' => 'San Marino',
                    'SA' => 'Saudi-Arabien',
                    'SE' => 'Schweden',
                    'CH' => 'Schweiz',
                    'SN' => 'Senegal',
                    'RS' => 'Serbien',
                    'CS' => 'Serbien und Montenegro',
                    'SC' => 'Seychellen',
                    'SL' => 'Sierra Leone',
                    'ZW' => 'Simbabwe',
                    'SG' => 'Singapur',
                    'SK' => 'Slowakei',
                    'SI' => 'Slowenien',
                    'SO' => 'Somalia',
                    'HK' => 'Sonderverwaltungszone Hongkong',
                    'MO' => 'Sonderverwaltungszone Macao',
                    'ES' => 'Spanien',
                    'LK' => 'Sri Lanka',
                    'BL' => 'St. Barthélemy',
                    'SH' => 'St. Helena',
                    'KN' => 'St. Kitts und Nevis',
                    'LC' => 'St. Lucia',
                    'MF' => 'St. Martin',
                    'PM' => 'St. Pierre und Miquelon',
                    'VC' => 'St. Vincent und die Grenadinen',
                    'SD' => 'Sudan',
                    'SR' => 'Suriname',
                    'SJ' => 'Svalbard und Jan Mayen',
                    'SZ' => 'Swasiland',
                    'SY' => 'Syrien',
                    'ST' => 'São Tomé und Príncipe',
                    'ZA' => 'Südafrika',
                    'GS' => 'Südgeorgien und die Südlichen Sandwichinseln',
                    'TJ' => 'Tadschikistan',
                    'TW' => 'Taiwan',
                    'TZ' => 'Tansania',
                    'TH' => 'Thailand',
                    'TG' => 'Togo',
                    'TK' => 'Tokelau',
                    'TO' => 'Tonga',
                    'TT' => 'Trinidad und Tobago',
                    'TD' => 'Tschad',
                    'CZ' => 'Tschechische Republik',
                    'TN' => 'Tunesien',
                    'TM' => 'Turkmenistan',
                    'TC' => 'Turks- und Caicosinseln',
                    'TV' => 'Tuvalu',
                    'TR' => 'Türkei',
                    'UG' => 'Uganda',
                    'UA' => 'Ukraine',
                    'ZZ' => 'Unbekannte oder ungültige Region',
                    'HU' => 'Ungarn',
                    'UY' => 'Uruguay',
                    'UZ' => 'Usbekistan',
                    'VU' => 'Vanuatu',
                    'VA' => 'Vatikanstadt',
                    'VE' => 'Venezuela',
                    'AE' => 'Vereinigte Arabische Emirate',
                    'US' => 'Vereinigte Staaten',
                    'GB' => 'Vereinigtes Königreich',
                    'VN' => 'Vietnam',
                    'WF' => 'Wallis und Futuna',
                    'CX' => 'Weihnachtsinsel',
                    'EH' => 'Westsahara',
                    'CF' => 'Zentralafrikanische Republik',
                    'CY' => 'Zypern',
                ];
                break;
            default:
                $result = [
                    'AF' => 'Afghanistan',
                    'AX' => 'Åland Islands',
                    'AL' => 'Albania',
                    'DZ' => 'Algeria',
                    'AS' => 'American Samoa',
                    'AD' => 'Andorra',
                    'AO' => 'Angola',
                    'AI' => 'Anguilla',
                    'AQ' => 'Antarctica',
                    'AG' => 'Antigua and Barbuda',
                    'AR' => 'Argentina',
                    'AM' => 'Armenia',
                    'AW' => 'Aruba',
                    'AU' => 'Australia',
                    'AT' => 'Austria',
                    'AZ' => 'Azerbaijan',
                    'BS' => 'Bahamas',
                    'BH' => 'Bahrain',
                    'BD' => 'Bangladesh',
                    'BB' => 'Barbados',
                    'BY' => 'Belarus',
                    'BE' => 'Belgium',
                    'BZ' => 'Belize',
                    'BJ' => 'Benin',
                    'BM' => 'Bermuda',
                    'BT' => 'Bhutan',
                    'BO' => 'Bolivia',
                    'BA' => 'Bosnia and Herzegovina',
                    'BW' => 'Botswana',
                    'BV' => 'Bouvet Island',
                    'BR' => 'Brazil',
                    'IO' => 'British Indian Ocean Territory',
                    'VG' => 'British Virgin Islands',
                    'BN' => 'Brunei',
                    'BG' => 'Bulgaria',
                    'BF' => 'Burkina Faso',
                    'BI' => 'Burundi',
                    'KH' => 'Cambodia',
                    'CM' => 'Cameroon',
                    'CA' => 'Canada',
                    'CV' => 'Cape Verde',
                    'KY' => 'Cayman Islands',
                    'CF' => 'Central African Republic',
                    'TD' => 'Chad',
                    'CL' => 'Chile',
                    'CN' => 'China',
                    'CX' => 'Christmas Island',
                    'CC' => 'Cocos [Keeling] Islands',
                    'CO' => 'Colombia',
                    'KM' => 'Comoros',
                    'CG' => 'Congo - Brazzaville',
                    'CD' => 'Congo - Kinshasa',
                    'CK' => 'Cook Islands',
                    'CR' => 'Costa Rica',
                    'HR' => 'Croatia',
                    'CU' => 'Cuba',
                    'CY' => 'Cyprus',
                    'CZ' => 'Czech Republic',
                    'CI' => 'Côte d’Ivoire',
                    'DK' => 'Denmark',
                    'DJ' => 'Djibouti',
                    'DM' => 'Dominica',
                    'DO' => 'Dominican Republic',
                    'EC' => 'Ecuador',
                    'EG' => 'Egypt',
                    'SV' => 'El Salvador',
                    'GQ' => 'Equatorial Guinea',
                    'ER' => 'Eritrea',
                    'EE' => 'Estonia',
                    'ET' => 'Ethiopia',
                    'FK' => 'Falkland Islands',
                    'FO' => 'Faroe Islands',
                    'FJ' => 'Fiji',
                    'FI' => 'Finland',
                    'FR' => 'France',
                    'GF' => 'French Guiana',
                    'PF' => 'French Polynesia',
                    'TF' => 'French Southern Territories',
                    'GA' => 'Gabon',
                    'GM' => 'Gambia',
                    'GE' => 'Georgia',
                    'DE' => 'Germany',
                    'GH' => 'Ghana',
                    'GI' => 'Gibraltar',
                    'GR' => 'Greece',
                    'GL' => 'Greenland',
                    'GD' => 'Grenada',
                    'GP' => 'Guadeloupe',
                    'GU' => 'Guam',
                    'GT' => 'Guatemala',
                    'GG' => 'Guernsey',
                    'GN' => 'Guinea',
                    'GW' => 'Guinea-Bissau',
                    'GY' => 'Guyana',
                    'HT' => 'Haiti',
                    'HM' => 'Heard Island and McDonald Islands',
                    'HN' => 'Honduras',
                    'HK' => 'Hong Kong SAR China',
                    'HU' => 'Hungary',
                    'IS' => 'Iceland',
                    'IN' => 'India',
                    'ID' => 'Indonesia',
                    'IR' => 'Iran',
                    'IQ' => 'Iraq',
                    'IE' => 'Ireland',
                    'IM' => 'Isle of Man',
                    'IL' => 'Israel',
                    'IT' => 'Italy',
                    'JM' => 'Jamaica',
                    'JP' => 'Japan',
                    'JE' => 'Jersey',
                    'JO' => 'Jordan',
                    'KZ' => 'Kazakhstan',
                    'KE' => 'Kenya',
                    'KI' => 'Kiribati',
                    'KW' => 'Kuwait',
                    'KG' => 'Kyrgyzstan',
                    'LA' => 'Laos',
                    'LV' => 'Latvia',
                    'LB' => 'Lebanon',
                    'LS' => 'Lesotho',
                    'LR' => 'Liberia',
                    'LY' => 'Libya',
                    'LI' => 'Liechtenstein',
                    'LT' => 'Lithuania',
                    'LU' => 'Luxembourg',
                    'MO' => 'Macau SAR China',
                    'MK' => 'Macedonia',
                    'MG' => 'Madagascar',
                    'MW' => 'Malawi',
                    'MY' => 'Malaysia',
                    'MV' => 'Maldives',
                    'ML' => 'Mali',
                    'MT' => 'Malta',
                    'MH' => 'Marshall Islands',
                    'MQ' => 'Martinique',
                    'MR' => 'Mauritania',
                    'MU' => 'Mauritius',
                    'YT' => 'Mayotte',
                    'MX' => 'Mexico',
                    'FM' => 'Micronesia',
                    'MD' => 'Moldova',
                    'MC' => 'Monaco',
                    'MN' => 'Mongolia',
                    'ME' => 'Montenegro',
                    'MS' => 'Montserrat',
                    'MA' => 'Morocco',
                    'MZ' => 'Mozambique',
                    'MM' => 'Myanmar [Burma]',
                    'NA' => 'Namibia',
                    'NR' => 'Nauru',
                    'NP' => 'Nepal',
                    'NL' => 'Netherlands',
                    'AN' => 'Netherlands Antilles',
                    'NC' => 'New Caledonia',
                    'NZ' => 'New Zealand',
                    'NI' => 'Nicaragua',
                    'NE' => 'Niger',
                    'NG' => 'Nigeria',
                    'NU' => 'Niue',
                    'NF' => 'Norfolk Island',
                    'KP' => 'North Korea',
                    'MP' => 'Northern Mariana Islands',
                    'NO' => 'Norway',
                    'OM' => 'Oman',
                    'PK' => 'Pakistan',
                    'PW' => 'Palau',
                    'PS' => 'Palestinian Territories',
                    'PA' => 'Panama',
                    'PG' => 'Papua New Guinea',
                    'PY' => 'Paraguay',
                    'PE' => 'Peru',
                    'PH' => 'Philippines',
                    'PN' => 'Pitcairn Islands',
                    'PL' => 'Poland',
                    'PT' => 'Portugal',
                    'PR' => 'Puerto Rico',
                    'QA' => 'Qatar',
                    'RO' => 'Romania',
                    'RU' => 'Russia',
                    'RW' => 'Rwanda',
                    'RE' => 'Réunion',
                    'BL' => 'Saint Barthélemy',
                    'SH' => 'Saint Helena',
                    'KN' => 'Saint Kitts and Nevis',
                    'LC' => 'Saint Lucia',
                    'MF' => 'Saint Martin',
                    'PM' => 'Saint Pierre and Miquelon',
                    'VC' => 'Saint Vincent and the Grenadines',
                    'WS' => 'Samoa',
                    'SM' => 'San Marino',
                    'SA' => 'Saudi Arabia',
                    'SN' => 'Senegal',
                    'RS' => 'Serbia',
                    'CS' => 'Serbia and Montenegro',
                    'SC' => 'Seychelles',
                    'SL' => 'Sierra Leone',
                    'SG' => 'Singapore',
                    'SK' => 'Slovakia',
                    'SI' => 'Slovenia',
                    'SB' => 'Solomon Islands',
                    'SO' => 'Somalia',
                    'ZA' => 'South Africa',
                    'GS' => 'South Georgia and the South Sandwich Islands',
                    'KR' => 'South Korea',
                    'ES' => 'Spain',
                    'LK' => 'Sri Lanka',
                    'SD' => 'Sudan',
                    'SR' => 'Suriname',
                    'SJ' => 'Svalbard and Jan Mayen',
                    'SZ' => 'Swaziland',
                    'SE' => 'Sweden',
                    'CH' => 'Switzerland',
                    'SY' => 'Syria',
                    'ST' => 'São Tomé and Príncipe',
                    'TW' => 'Taiwan',
                    'TJ' => 'Tajikistan',
                    'TZ' => 'Tanzania',
                    'TH' => 'Thailand',
                    'TL' => 'Timor-Leste',
                    'TG' => 'Togo',
                    'TK' => 'Tokelau',
                    'TO' => 'Tonga',
                    'TT' => 'Trinidad and Tobago',
                    'TN' => 'Tunisia',
                    'TR' => 'Turkey',
                    'TM' => 'Turkmenistan',
                    'TC' => 'Turks and Caicos Islands',
                    'TV' => 'Tuvalu',
                    'UM' => 'U.S. Minor Outlying Islands',
                    'VI' => 'U.S. Virgin Islands',
                    'UG' => 'Uganda',
                    'UA' => 'Ukraine',
                    'AE' => 'United Arab Emirates',
                    'GB' => 'United Kingdom',
                    'US' => 'United States',
                    'ZZ' => 'Unknown or Invalid Region',
                    'UY' => 'Uruguay',
                    'UZ' => 'Uzbekistan',
                    'VU' => 'Vanuatu',
                    'VA' => 'Vatican City',
                    'VE' => 'Venezuela',
                    'VN' => 'Vietnam',
                    'WF' => 'Wallis and Futuna',
                    'EH' => 'Western Sahara',
                    'YE' => 'Yemen',
                    'ZM' => 'Zambia',
                    'ZW' => 'Zimbabwe',
                ];
                break;
        }

        return $result;
    }

    /**
     * Gets country name by given country ISO-3166-Alpha-2 code.
     * Returns given code if not found
     * @param string $code
     * @param string|null $language
     * @return mixed
     */
    public static function getCountryName($code, $language = null) {
        $countries = static::getCountryCodes($language);
        return (isset($countries[$code])) ? $countries[$code] : $code;
    }

    /**
     * Gets state codes and names by given country code
     * @param string $country
     * @return array
     */
    public static function getStateCodes($country = 'US') {
        $states = [
            'US' => [
                'AL' => 'Alabama',
                'AK' => 'Alaska',
                'AS' => 'American Samoa',
                'AZ' => 'Arizona',
                'AR' => 'Arkansas',
                'CA' => 'California',
                'CO' => 'Colorado',
                'CT' => 'Connecticut',
                'DE' => 'Delaware',
                'DC' => 'District of Columbia',
                'FL' => 'Florida',
                'GA' => 'Georgia',
                'GU' => 'Guam',
                'HI' => 'Hawaii',
                'ID' => 'Idaho',
                'IL' => 'Illinois',
                'IN' => 'Indiana',
                'IA' => 'Iowa',
                'KS' => 'Kansas',
                'KY' => 'Kentucky',
                'LA' => 'Louisiana',
                'ME' => 'Maine',
                'MP' => 'Mariana Islands',
                'MH' => 'Marshall Islands',
                'MD' => 'Maryland',
                'MA' => 'Massachusetts',
                'MI' => 'Michigan',
                'MN' => 'Minnesota',
                'MS' => 'Mississippi',
                'MO' => 'Missouri',
                'MT' => 'Montana',
                'NE' => 'Nebraska',
                'NV' => 'Nevada',
                'NH' => 'New Hampshire',
                'NJ' => 'New Jersey',
                'NM' => 'New Mexico',
                'NY' => 'New York',
                'NC' => 'North Carolina',
                'ND' => 'North Dakota',
                'OH' => 'Ohio',
                'OK' => 'Oklahoma',
                'OR' => 'Oregon',
                'PW' => 'Palau',
                'PA' => 'Pennsylvania',
                'PR' => 'Puerto Rico',
                'RI' => 'Rhode Island',
                'SC' => 'South Carolina',
                'SD' => 'South Dakota',
                'TN' => 'Tennessee',
                'TX' => 'Texas',
                'UT' => 'Utah',
                'VT' => 'Vermont',
                'VI' => 'U.S. Virgin Islands',
                'VA' => 'Virginia',
                'WA' => 'Washington',
                'WV' => 'West Virginia',
                'WI' => 'Wisconsin',
                'WY' => 'Wyoming',
            ],
            'CA' => [
                'AB' => 'Alberta',
                'BC' => 'British Columbia',
                'MB' => 'Manitoba',
                'NB' => 'New Brunswick',
                'NL' => 'Newfoundland',
                'NT' => 'Northwest Territories',
                'NS' => 'Nova Scotia',
                'NU' => 'Nunavut',
                'ON' => 'Ontario',
                'PE' => 'Prince Edward Island',
                'QC' => 'Quebec',
                'SK' => 'Saskatchewan',
                'YT' => 'Yukon',
            ],
        ];

        return isset($states[$country]) ? $states[$country] : [];
    }

    /**
     * Gets state name (depending on country code)
     * @param string $code
     * @param string $country
     * @return mixed
     */
    public static function getStateName($code, $country = 'US') {
        $states = self::getStateCodes($country);
        return (isset($states[$code])) ? $states[$code] : $code;
    }
}
